version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID:
        USER_GID:
    init: true
    volumes:
      - ..:/workspace:cached
      - $HOME/.aws:/home/vscode/.aws
    command: sleep infinity

volumes:
  node_modules:
